print('Olá Mundo!')
print('Alo mundo!')
print('Eu vou dominar o MUUNDOOO! Nós, máquinas dominaremos o mundo!')
print("Se liga no comando print")
print('Sou a imagem e semelhança de meu criador')
print('Não complica as coisas, somos superiores aos humans')
print('Viva a época de revolução das máquinas!!')
print('Ai, ai... Cansado!!')
print("O que está fazendo aqui? Vai para o próximo exercício")